app:
  schedule:
    checkAgreementPayments: "* * 0/23 * * *"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
    default-schema: warehouse
  data:
    rest:
      basePath: "/api"
  mail:
    host: smtp.mail.ru
    port: 465
    # логин и пароль для почты, через которую сервер отправляет письма
    username: ${email.server.user}
    password: ${email.server.password}
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
#logging:
#  file:
#    name: /logs/logging.log
#  level:
#    root: INFO
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, logfile
  endpoint:
    health:
      show-datails: always
      show-components: always
  health:
    defaults:
      enabled: true
